version: '3'

services:
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
     - PMA_ARBITRARY=1
   restart: always
   ports:
     - 8082:80
   volumes:
     - /sessions

 db-lavajato:
   image: "thidemello/db-lavajato:3.0"
   container_name: db-lavajato
   environment:
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=lavajato
     - MYSQL_PASS=lavajato
     - MYSQL_DATABASE=lavajato
   volumes:
     - my-datavolume:/var/lib/mysql/
   restart: always

 backend:
   image: "thidemello/back-lavajato:1.0"
   container_name: back-lavajato
   command: python manage.py runserver 0.0.0.0:8000
   ports:
      - "8000:8000"
   depends_on:
      - db-lavajato

 frontend:
   image: "thidemello/front-lavajato:1.0"
   container_name: front-lavajato
   ports: 
     - "8001:8001"

volumes:
 my-datavolume:

